// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module clefia_ClefiaKeySet128 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        rk_address0,
        rk_ce0,
        rk_we0,
        rk_d0,
        rk_address1,
        rk_ce1,
        rk_we1,
        rk_d1
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] rk_address0;
output   rk_ce0;
output   rk_we0;
output  [7:0] rk_d0;
output  [7:0] rk_address1;
output   rk_ce1;
output   rk_we1;
output  [7:0] rk_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[7:0] rk_address0;
reg rk_ce0;
reg rk_we0;
reg[7:0] rk_d0;
reg rk_ce1;
reg rk_we1;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [7:0] con128_address0;
reg    con128_ce0;
wire   [7:0] con128_q0;
reg   [3:0] fin_address0;
reg    fin_ce0;
reg    fin_we0;
reg   [7:0] fin_d0;
wire   [7:0] fin_q0;
reg    fin_ce1;
reg    fin_we1;
wire   [7:0] fin_q1;
reg   [3:0] fout_address0;
reg    fout_ce0;
reg    fout_we0;
wire   [7:0] fout_q0;
reg    fout_ce1;
reg    fout_we1;
wire   [7:0] fout_q1;
reg   [3:0] lk_address0;
reg    lk_ce0;
reg    lk_we0;
reg   [7:0] lk_d0;
wire   [7:0] lk_q0;
reg    lk_ce1;
reg    lk_we1;
wire   [7:0] lk_q1;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1_fu_36_ap_start;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1_fu_36_ap_done;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1_fu_36_ap_idle;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1_fu_36_ap_ready;
wire   [3:0] grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1_fu_36_fin_address0;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1_fu_36_fin_ce0;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1_fu_36_fin_we0;
wire   [7:0] grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1_fu_36_fin_d0;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_ap_start;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_ap_done;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_ap_idle;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_ap_ready;
wire   [3:0] grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fin_address0;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fin_ce0;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fin_we0;
wire   [7:0] grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fin_d0;
wire   [3:0] grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fin_address1;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fin_ce1;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fin_we1;
wire   [7:0] grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fin_d1;
wire   [3:0] grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fout_address0;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fout_ce0;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fout_we0;
wire   [7:0] grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fout_d0;
wire   [3:0] grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fout_address1;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fout_ce1;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fout_we1;
wire   [7:0] grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fout_d1;
wire   [7:0] grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_con128_address0;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_con128_ce0;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_116_fu_56_ap_start;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_116_fu_56_ap_done;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_116_fu_56_ap_idle;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_116_fu_56_ap_ready;
wire   [7:0] grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_116_fu_56_rk_address0;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_116_fu_56_rk_ce0;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_116_fu_56_rk_we0;
wire   [7:0] grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_116_fu_56_rk_d0;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_ap_start;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_ap_done;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_ap_idle;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_ap_ready;
wire   [3:0] grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_fout_address0;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_fout_ce0;
wire   [3:0] grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_lk_address0;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_lk_ce0;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_lk_we0;
wire   [7:0] grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_lk_d0;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_ap_start;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_ap_done;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_ap_idle;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_ap_ready;
wire   [3:0] grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_lk_address0;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_lk_ce0;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_lk_we0;
wire   [7:0] grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_lk_d0;
wire   [3:0] grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_lk_address1;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_lk_ce1;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_lk_we1;
wire   [7:0] grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_lk_d1;
wire   [7:0] grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_rk_address0;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_rk_ce0;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_rk_we0;
wire   [7:0] grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_rk_d0;
wire   [7:0] grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_rk_address1;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_rk_ce1;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_rk_we1;
wire   [7:0] grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_rk_d1;
wire   [7:0] grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_con128_address0;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_con128_ce0;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_ap_start;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_ap_done;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_ap_idle;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_ap_ready;
wire   [7:0] grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_rk_address0;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_rk_ce0;
wire    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_rk_we0;
wire   [7:0] grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_rk_d0;
reg    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1_fu_36_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_116_fu_56_ap_start_reg;
reg    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg    grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_block_state4_on_subcall_done;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1_fu_36_ap_start_reg = 1'b0;
#0 grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_ap_start_reg = 1'b0;
#0 grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_116_fu_56_ap_start_reg = 1'b0;
#0 grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_ap_start_reg = 1'b0;
#0 grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_ap_start_reg = 1'b0;
#0 grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_ap_start_reg = 1'b0;
end

clefia_ClefiaKeySet128_con128_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 240 ),
    .AddressWidth( 8 ))
con128_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(con128_address0),
    .ce0(con128_ce0),
    .q0(con128_q0)
);

clefia_ClefiaKeySet128_fin_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
fin_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fin_address0),
    .ce0(fin_ce0),
    .we0(fin_we0),
    .d0(fin_d0),
    .q0(fin_q0),
    .address1(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fin_address1),
    .ce1(fin_ce1),
    .we1(fin_we1),
    .d1(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fin_d1),
    .q1(fin_q1)
);

clefia_ClefiaKeySet128_fin_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
fout_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fout_address0),
    .ce0(fout_ce0),
    .we0(fout_we0),
    .d0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fout_d0),
    .q0(fout_q0),
    .address1(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fout_address1),
    .ce1(fout_ce1),
    .we1(fout_we1),
    .d1(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fout_d1),
    .q1(fout_q1)
);

clefia_ClefiaKeySet128_fin_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
lk_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lk_address0),
    .ce0(lk_ce0),
    .we0(lk_we0),
    .d0(lk_d0),
    .q0(lk_q0),
    .address1(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_lk_address1),
    .ce1(lk_ce1),
    .we1(lk_we1),
    .d1(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_lk_d1),
    .q1(lk_q1)
);

clefia_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1 grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1_fu_36(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1_fu_36_ap_start),
    .ap_done(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1_fu_36_ap_done),
    .ap_idle(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1_fu_36_ap_idle),
    .ap_ready(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1_fu_36_ap_ready),
    .fin_address0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1_fu_36_fin_address0),
    .fin_ce0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1_fu_36_fin_ce0),
    .fin_we0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1_fu_36_fin_we0),
    .fin_d0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1_fu_36_fin_d0)
);

clefia_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1 grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_ap_start),
    .ap_done(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_ap_done),
    .ap_idle(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_ap_idle),
    .ap_ready(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_ap_ready),
    .fin_address0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fin_address0),
    .fin_ce0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fin_ce0),
    .fin_we0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fin_we0),
    .fin_d0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fin_d0),
    .fin_q0(fin_q0),
    .fin_address1(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fin_address1),
    .fin_ce1(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fin_ce1),
    .fin_we1(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fin_we1),
    .fin_d1(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fin_d1),
    .fin_q1(fin_q1),
    .fout_address0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fout_address0),
    .fout_ce0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fout_ce0),
    .fout_we0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fout_we0),
    .fout_d0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fout_d0),
    .fout_q0(fout_q0),
    .fout_address1(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fout_address1),
    .fout_ce1(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fout_ce1),
    .fout_we1(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fout_we1),
    .fout_d1(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fout_d1),
    .fout_q1(fout_q1),
    .con128_address0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_con128_address0),
    .con128_ce0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_con128_ce0),
    .con128_q0(con128_q0)
);

clefia_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_116 grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_116_fu_56(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_116_fu_56_ap_start),
    .ap_done(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_116_fu_56_ap_done),
    .ap_idle(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_116_fu_56_ap_idle),
    .ap_ready(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_116_fu_56_ap_ready),
    .rk_address0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_116_fu_56_rk_address0),
    .rk_ce0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_116_fu_56_rk_ce0),
    .rk_we0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_116_fu_56_rk_we0),
    .rk_d0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_116_fu_56_rk_d0)
);

clefia_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115 grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_ap_start),
    .ap_done(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_ap_done),
    .ap_idle(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_ap_idle),
    .ap_ready(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_ap_ready),
    .fout_address0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_fout_address0),
    .fout_ce0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_fout_ce0),
    .fout_q0(fout_q0),
    .lk_address0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_lk_address0),
    .lk_ce0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_lk_ce0),
    .lk_we0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_lk_we0),
    .lk_d0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_lk_d0)
);

clefia_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1 grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_ap_start),
    .ap_done(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_ap_done),
    .ap_idle(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_ap_idle),
    .ap_ready(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_ap_ready),
    .lk_address0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_lk_address0),
    .lk_ce0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_lk_ce0),
    .lk_we0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_lk_we0),
    .lk_d0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_lk_d0),
    .lk_q0(lk_q0),
    .lk_address1(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_lk_address1),
    .lk_ce1(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_lk_ce1),
    .lk_we1(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_lk_we1),
    .lk_d1(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_lk_d1),
    .lk_q1(lk_q1),
    .rk_address0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_rk_address0),
    .rk_ce0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_rk_ce0),
    .rk_we0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_rk_we0),
    .rk_d0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_rk_d0),
    .rk_address1(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_rk_address1),
    .rk_ce1(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_rk_ce1),
    .rk_we1(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_rk_we1),
    .rk_d1(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_rk_d1),
    .con128_address0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_con128_address0),
    .con128_ce0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_con128_ce0),
    .con128_q0(con128_q0)
);

clefia_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117 grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_ap_start),
    .ap_done(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_ap_done),
    .ap_idle(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_ap_idle),
    .ap_ready(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_ap_ready),
    .rk_address0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_rk_address0),
    .rk_ce0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_rk_ce0),
    .rk_we0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_rk_we0),
    .rk_d0(grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_rk_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_ap_start_reg <= 1'b1;
        end else if ((grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_ap_ready == 1'b1)) begin
            grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_116_fu_56_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_116_fu_56_ap_start_reg <= 1'b1;
        end else if ((grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_116_fu_56_ap_ready == 1'b1)) begin
            grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_116_fu_56_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_ap_start_reg <= 1'b1;
        end else if ((grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_ap_ready == 1'b1)) begin
            grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1_fu_36_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1_fu_36_ap_start_reg <= 1'b1;
        end else if ((grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1_fu_36_ap_ready == 1'b1)) begin
            grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1_fu_36_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_ap_start_reg <= 1'b1;
        end else if ((grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_ap_ready == 1'b1)) begin
            grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_ap_start_reg <= 1'b1;
        end else if ((grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_ap_ready == 1'b1)) begin
            grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1_fu_36_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state4_on_subcall_done)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state10) & (grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_ap_done == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        con128_address0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_con128_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        con128_address0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_con128_address0;
    end else begin
        con128_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        con128_ce0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_con128_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        con128_ce0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_con128_ce0;
    end else begin
        con128_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fin_address0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fin_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        fin_address0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1_fu_36_fin_address0;
    end else begin
        fin_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fin_ce0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fin_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        fin_ce0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1_fu_36_fin_ce0;
    end else begin
        fin_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fin_ce1 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fin_ce1;
    end else begin
        fin_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fin_d0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fin_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        fin_d0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1_fu_36_fin_d0;
    end else begin
        fin_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fin_we0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fin_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        fin_we0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1_fu_36_fin_we0;
    end else begin
        fin_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fin_we1 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fin_we1;
    end else begin
        fin_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        fout_address0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_fout_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        fout_address0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fout_address0;
    end else begin
        fout_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        fout_ce0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_fout_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        fout_ce0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fout_ce0;
    end else begin
        fout_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fout_ce1 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fout_ce1;
    end else begin
        fout_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fout_we0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fout_we0;
    end else begin
        fout_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fout_we1 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_fout_we1;
    end else begin
        fout_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        lk_address0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_lk_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        lk_address0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_lk_address0;
    end else begin
        lk_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        lk_ce0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_lk_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        lk_ce0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_lk_ce0;
    end else begin
        lk_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        lk_ce1 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_lk_ce1;
    end else begin
        lk_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        lk_d0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_lk_d0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        lk_d0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_lk_d0;
    end else begin
        lk_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        lk_we0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_lk_we0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        lk_we0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_lk_we0;
    end else begin
        lk_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        lk_we1 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_lk_we1;
    end else begin
        lk_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        rk_address0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_rk_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        rk_address0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_rk_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        rk_address0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_116_fu_56_rk_address0;
    end else begin
        rk_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        rk_ce0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_rk_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        rk_ce0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_rk_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        rk_ce0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_116_fu_56_rk_ce0;
    end else begin
        rk_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        rk_ce1 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_rk_ce1;
    end else begin
        rk_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        rk_d0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_rk_d0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        rk_d0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_rk_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        rk_d0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_116_fu_56_rk_d0;
    end else begin
        rk_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        rk_we0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_rk_we0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        rk_we0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_rk_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        rk_we0 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_116_fu_56_rk_we0;
    end else begin
        rk_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        rk_we1 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_rk_we1;
    end else begin
        rk_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1_fu_36_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state4_on_subcall_done = ((grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_116_fu_56_ap_done == 1'b0) | (grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_ap_done == 1'b0));
end

assign grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_ap_start = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_115_fu_64_ap_start_reg;

assign grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_116_fu_56_ap_start = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_116_fu_56_ap_start_reg;

assign grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_ap_start = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_117_fu_79_ap_start_reg;

assign grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1_fu_36_ap_start = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_116_1_fu_36_ap_start_reg;

assign grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_ap_start = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_193_1_fu_44_ap_start_reg;

assign grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_ap_start = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_ap_start_reg;

assign rk_address1 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_rk_address1;

assign rk_d1 = grp_ClefiaKeySet128_Pipeline_VITIS_LOOP_309_1_fu_70_rk_d1;

endmodule //clefia_ClefiaKeySet128
