set SynModuleInfo {
  {SRCNAME clefia_Pipeline_ByteCpy_label157 MODELNAME clefia_Pipeline_ByteCpy_label157 RTLNAME clefia_clefia_Pipeline_ByteCpy_label157
    SUBMODULES {
      {MODELNAME clefia_clefia_Pipeline_ByteCpy_label157_skey_ROM_AUTO_1R RTLNAME clefia_clefia_Pipeline_ByteCpy_label157_skey_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME clefia_flow_control_loop_pipe_sequential_init RTLNAME clefia_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME clefia_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME clefia_Pipeline_ClefiaGfn8_label458 MODELNAME clefia_Pipeline_ClefiaGfn8_label458 RTLNAME clefia_clefia_Pipeline_ClefiaGfn8_label458}
  {SRCNAME clefia_Pipeline_ByteCpy_label159 MODELNAME clefia_Pipeline_ByteCpy_label159 RTLNAME clefia_clefia_Pipeline_ByteCpy_label159}
  {SRCNAME clefia_Pipeline_ByteXor_label260 MODELNAME clefia_Pipeline_ByteXor_label260 RTLNAME clefia_clefia_Pipeline_ByteXor_label260
    SUBMODULES {
      {MODELNAME clefia_clefia_Pipeline_ByteXor_label260_skey_ROM_AUTO_1R RTLNAME clefia_clefia_Pipeline_ByteXor_label260_skey_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME clefia_Pipeline_ClefiaKeySet256_label10 MODELNAME clefia_Pipeline_ClefiaKeySet256_label10 RTLNAME clefia_clefia_Pipeline_ClefiaKeySet256_label10}
  {SRCNAME clefia_Pipeline_ByteXor_label261 MODELNAME clefia_Pipeline_ByteXor_label261 RTLNAME clefia_clefia_Pipeline_ByteXor_label261}
  {SRCNAME clefia_Pipeline_ByteCpy_label152 MODELNAME clefia_Pipeline_ByteCpy_label152 RTLNAME clefia_clefia_Pipeline_ByteCpy_label152}
  {SRCNAME clefia_Pipeline_ClefiaKeySet192_label8 MODELNAME clefia_Pipeline_ClefiaKeySet192_label8 RTLNAME clefia_clefia_Pipeline_ClefiaKeySet192_label8}
  {SRCNAME clefia_Pipeline_ByteCpy_label153 MODELNAME clefia_Pipeline_ByteCpy_label153 RTLNAME clefia_clefia_Pipeline_ByteCpy_label153}
  {SRCNAME clefia_Pipeline_ClefiaGfn8_label4 MODELNAME clefia_Pipeline_ClefiaGfn8_label4 RTLNAME clefia_clefia_Pipeline_ClefiaGfn8_label4}
  {SRCNAME clefia_Pipeline_ByteCpy_label154 MODELNAME clefia_Pipeline_ByteCpy_label154 RTLNAME clefia_clefia_Pipeline_ByteCpy_label154}
  {SRCNAME clefia_Pipeline_ByteXor_label255 MODELNAME clefia_Pipeline_ByteXor_label255 RTLNAME clefia_clefia_Pipeline_ByteXor_label255}
  {SRCNAME clefia_Pipeline_ClefiaKeySet192_label9 MODELNAME clefia_Pipeline_ClefiaKeySet192_label9 RTLNAME clefia_clefia_Pipeline_ClefiaKeySet192_label9}
  {SRCNAME clefia_Pipeline_ByteXor_label256 MODELNAME clefia_Pipeline_ByteXor_label256 RTLNAME clefia_clefia_Pipeline_ByteXor_label256}
  {SRCNAME clefia_Pipeline_ByteCpy_label1 MODELNAME clefia_Pipeline_ByteCpy_label1 RTLNAME clefia_clefia_Pipeline_ByteCpy_label1}
  {SRCNAME clefia_Pipeline_ClefiaGfn4_label3 MODELNAME clefia_Pipeline_ClefiaGfn4_label3 RTLNAME clefia_clefia_Pipeline_ClefiaGfn4_label3}
  {SRCNAME clefia_Pipeline_ByteCpy_label128 MODELNAME clefia_Pipeline_ByteCpy_label128 RTLNAME clefia_clefia_Pipeline_ByteCpy_label128}
  {SRCNAME clefia_Pipeline_ByteCpy_label129 MODELNAME clefia_Pipeline_ByteCpy_label129 RTLNAME clefia_clefia_Pipeline_ByteCpy_label129}
  {SRCNAME clefia_Pipeline_ByteXor_label2 MODELNAME clefia_Pipeline_ByteXor_label2 RTLNAME clefia_clefia_Pipeline_ByteXor_label2}
  {SRCNAME clefia_Pipeline_ByteCpy_label130 MODELNAME clefia_Pipeline_ByteCpy_label130 RTLNAME clefia_clefia_Pipeline_ByteCpy_label130}
  {SRCNAME clefia_Pipeline_ByteXor_label231 MODELNAME clefia_Pipeline_ByteXor_label231 RTLNAME clefia_clefia_Pipeline_ByteXor_label231}
  {SRCNAME clefia_Pipeline_ByteXor_label232 MODELNAME clefia_Pipeline_ByteXor_label232 RTLNAME clefia_clefia_Pipeline_ByteXor_label232}
  {SRCNAME clefia_Pipeline_ByteCpy_label133 MODELNAME clefia_Pipeline_ByteCpy_label133 RTLNAME clefia_clefia_Pipeline_ByteCpy_label133}
  {SRCNAME clefia_Pipeline_ByteXor_label234 MODELNAME clefia_Pipeline_ByteXor_label234 RTLNAME clefia_clefia_Pipeline_ByteXor_label234}
  {SRCNAME clefia_Pipeline_ByteCpy_label135 MODELNAME clefia_Pipeline_ByteCpy_label135 RTLNAME clefia_clefia_Pipeline_ByteCpy_label135}
  {SRCNAME clefia_Pipeline_ByteXor_label236 MODELNAME clefia_Pipeline_ByteXor_label236 RTLNAME clefia_clefia_Pipeline_ByteXor_label236}
  {SRCNAME clefia_Pipeline_ByteXor_label237 MODELNAME clefia_Pipeline_ByteXor_label237 RTLNAME clefia_clefia_Pipeline_ByteXor_label237}
  {SRCNAME clefia_Pipeline_ByteCpy_label138 MODELNAME clefia_Pipeline_ByteCpy_label138 RTLNAME clefia_clefia_Pipeline_ByteCpy_label138}
  {SRCNAME clefia_Pipeline_ByteXor_label239 MODELNAME clefia_Pipeline_ByteXor_label239 RTLNAME clefia_clefia_Pipeline_ByteXor_label239}
  {SRCNAME clefia_Pipeline_ByteCpy_label140 MODELNAME clefia_Pipeline_ByteCpy_label140 RTLNAME clefia_clefia_Pipeline_ByteCpy_label140}
  {SRCNAME clefia_Pipeline_ByteXor_label241 MODELNAME clefia_Pipeline_ByteXor_label241 RTLNAME clefia_clefia_Pipeline_ByteXor_label241}
  {SRCNAME clefia_Pipeline_ByteXor_label242 MODELNAME clefia_Pipeline_ByteXor_label242 RTLNAME clefia_clefia_Pipeline_ByteXor_label242}
  {SRCNAME clefia_Pipeline_ByteCpy_label143 MODELNAME clefia_Pipeline_ByteCpy_label143 RTLNAME clefia_clefia_Pipeline_ByteCpy_label143}
  {SRCNAME clefia_Pipeline_ByteXor_label244 MODELNAME clefia_Pipeline_ByteXor_label244 RTLNAME clefia_clefia_Pipeline_ByteXor_label244}
  {SRCNAME clefia_Pipeline_ByteCpy_label145 MODELNAME clefia_Pipeline_ByteCpy_label145 RTLNAME clefia_clefia_Pipeline_ByteCpy_label145}
  {SRCNAME clefia_Pipeline_ByteXor_label246 MODELNAME clefia_Pipeline_ByteXor_label246 RTLNAME clefia_clefia_Pipeline_ByteXor_label246}
  {SRCNAME clefia_Pipeline_ByteXor_label247 MODELNAME clefia_Pipeline_ByteXor_label247 RTLNAME clefia_clefia_Pipeline_ByteXor_label247}
  {SRCNAME clefia_Pipeline_ByteCpy_label148 MODELNAME clefia_Pipeline_ByteCpy_label148 RTLNAME clefia_clefia_Pipeline_ByteCpy_label148}
  {SRCNAME clefia_Pipeline_ByteXor_label249 MODELNAME clefia_Pipeline_ByteXor_label249 RTLNAME clefia_clefia_Pipeline_ByteXor_label249}
  {SRCNAME clefia_Pipeline_ByteCpy_label150 MODELNAME clefia_Pipeline_ByteCpy_label150 RTLNAME clefia_clefia_Pipeline_ByteCpy_label150}
  {SRCNAME clefia_Pipeline_ByteCpy_label151 MODELNAME clefia_Pipeline_ByteCpy_label151 RTLNAME clefia_clefia_Pipeline_ByteCpy_label151}
  {SRCNAME clefia_Pipeline_ByteCpy_label162 MODELNAME clefia_Pipeline_ByteCpy_label162 RTLNAME clefia_clefia_Pipeline_ByteCpy_label162}
  {SRCNAME clefia_Pipeline_ByteXor_label263 MODELNAME clefia_Pipeline_ByteXor_label263 RTLNAME clefia_clefia_Pipeline_ByteXor_label263}
  {SRCNAME clefia_Pipeline_ByteXor_label264 MODELNAME clefia_Pipeline_ByteXor_label264 RTLNAME clefia_clefia_Pipeline_ByteXor_label264}
  {SRCNAME clefia_Pipeline_ByteCpy_label165 MODELNAME clefia_Pipeline_ByteCpy_label165 RTLNAME clefia_clefia_Pipeline_ByteCpy_label165}
  {SRCNAME clefia_Pipeline_ClefiaGfn4_label366 MODELNAME clefia_Pipeline_ClefiaGfn4_label366 RTLNAME clefia_clefia_Pipeline_ClefiaGfn4_label366}
  {SRCNAME clefia_Pipeline_ByteCpy_label167 MODELNAME clefia_Pipeline_ByteCpy_label167 RTLNAME clefia_clefia_Pipeline_ByteCpy_label167}
  {SRCNAME clefia_Pipeline_ByteCpy_label168 MODELNAME clefia_Pipeline_ByteCpy_label168 RTLNAME clefia_clefia_Pipeline_ByteCpy_label168}
  {SRCNAME clefia_Pipeline_ByteXor_label269 MODELNAME clefia_Pipeline_ByteXor_label269 RTLNAME clefia_clefia_Pipeline_ByteXor_label269}
  {SRCNAME clefia_Pipeline_ByteXor_label270 MODELNAME clefia_Pipeline_ByteXor_label270 RTLNAME clefia_clefia_Pipeline_ByteXor_label270}
  {SRCNAME clefia_Pipeline_ByteCpy_label171 MODELNAME clefia_Pipeline_ByteCpy_label171 RTLNAME clefia_clefia_Pipeline_ByteCpy_label171}
  {SRCNAME clefia_Pipeline_ByteCpy_label1107 MODELNAME clefia_Pipeline_ByteCpy_label1107 RTLNAME clefia_clefia_Pipeline_ByteCpy_label1107}
  {SRCNAME clefia_Pipeline_ClefiaGfn8_label4108 MODELNAME clefia_Pipeline_ClefiaGfn8_label4108 RTLNAME clefia_clefia_Pipeline_ClefiaGfn8_label4108}
  {SRCNAME clefia_Pipeline_ByteCpy_label1109 MODELNAME clefia_Pipeline_ByteCpy_label1109 RTLNAME clefia_clefia_Pipeline_ByteCpy_label1109}
  {SRCNAME clefia_Pipeline_ByteXor_label2110 MODELNAME clefia_Pipeline_ByteXor_label2110 RTLNAME clefia_clefia_Pipeline_ByteXor_label2110}
  {SRCNAME clefia_Pipeline_ClefiaKeySet256_label10111 MODELNAME clefia_Pipeline_ClefiaKeySet256_label10111 RTLNAME clefia_clefia_Pipeline_ClefiaKeySet256_label10111}
  {SRCNAME clefia_Pipeline_ByteXor_label2112 MODELNAME clefia_Pipeline_ByteXor_label2112 RTLNAME clefia_clefia_Pipeline_ByteXor_label2112}
  {SRCNAME clefia_Pipeline_ByteCpy_label199 MODELNAME clefia_Pipeline_ByteCpy_label199 RTLNAME clefia_clefia_Pipeline_ByteCpy_label199}
  {SRCNAME clefia_Pipeline_ClefiaKeySet192_label8100 MODELNAME clefia_Pipeline_ClefiaKeySet192_label8100 RTLNAME clefia_clefia_Pipeline_ClefiaKeySet192_label8100}
  {SRCNAME clefia_Pipeline_ByteCpy_label1101 MODELNAME clefia_Pipeline_ByteCpy_label1101 RTLNAME clefia_clefia_Pipeline_ByteCpy_label1101}
  {SRCNAME clefia_Pipeline_ClefiaGfn8_label4102 MODELNAME clefia_Pipeline_ClefiaGfn8_label4102 RTLNAME clefia_clefia_Pipeline_ClefiaGfn8_label4102}
  {SRCNAME clefia_Pipeline_ByteCpy_label1103 MODELNAME clefia_Pipeline_ByteCpy_label1103 RTLNAME clefia_clefia_Pipeline_ByteCpy_label1103}
  {SRCNAME clefia_Pipeline_ByteXor_label2104 MODELNAME clefia_Pipeline_ByteXor_label2104 RTLNAME clefia_clefia_Pipeline_ByteXor_label2104}
  {SRCNAME clefia_Pipeline_ClefiaKeySet192_label9105 MODELNAME clefia_Pipeline_ClefiaKeySet192_label9105 RTLNAME clefia_clefia_Pipeline_ClefiaKeySet192_label9105}
  {SRCNAME clefia_Pipeline_ByteXor_label2106 MODELNAME clefia_Pipeline_ByteXor_label2106 RTLNAME clefia_clefia_Pipeline_ByteXor_label2106}
  {SRCNAME clefia_Pipeline_ByteCpy_label172 MODELNAME clefia_Pipeline_ByteCpy_label172 RTLNAME clefia_clefia_Pipeline_ByteCpy_label172}
  {SRCNAME clefia_Pipeline_ClefiaGfn4_label373 MODELNAME clefia_Pipeline_ClefiaGfn4_label373 RTLNAME clefia_clefia_Pipeline_ClefiaGfn4_label373}
  {SRCNAME clefia_Pipeline_ByteCpy_label174 MODELNAME clefia_Pipeline_ByteCpy_label174 RTLNAME clefia_clefia_Pipeline_ByteCpy_label174}
  {SRCNAME clefia_Pipeline_ByteCpy_label175 MODELNAME clefia_Pipeline_ByteCpy_label175 RTLNAME clefia_clefia_Pipeline_ByteCpy_label175}
  {SRCNAME clefia_Pipeline_ByteXor_label276 MODELNAME clefia_Pipeline_ByteXor_label276 RTLNAME clefia_clefia_Pipeline_ByteXor_label276}
  {SRCNAME clefia_Pipeline_ByteCpy_label177 MODELNAME clefia_Pipeline_ByteCpy_label177 RTLNAME clefia_clefia_Pipeline_ByteCpy_label177}
  {SRCNAME clefia_Pipeline_ByteXor_label278 MODELNAME clefia_Pipeline_ByteXor_label278 RTLNAME clefia_clefia_Pipeline_ByteXor_label278}
  {SRCNAME clefia_Pipeline_ByteXor_label279 MODELNAME clefia_Pipeline_ByteXor_label279 RTLNAME clefia_clefia_Pipeline_ByteXor_label279}
  {SRCNAME clefia_Pipeline_ByteCpy_label180 MODELNAME clefia_Pipeline_ByteCpy_label180 RTLNAME clefia_clefia_Pipeline_ByteCpy_label180}
  {SRCNAME clefia_Pipeline_ByteXor_label281 MODELNAME clefia_Pipeline_ByteXor_label281 RTLNAME clefia_clefia_Pipeline_ByteXor_label281}
  {SRCNAME clefia_Pipeline_ByteCpy_label182 MODELNAME clefia_Pipeline_ByteCpy_label182 RTLNAME clefia_clefia_Pipeline_ByteCpy_label182}
  {SRCNAME clefia_Pipeline_ByteXor_label283 MODELNAME clefia_Pipeline_ByteXor_label283 RTLNAME clefia_clefia_Pipeline_ByteXor_label283}
  {SRCNAME clefia_Pipeline_ByteXor_label284 MODELNAME clefia_Pipeline_ByteXor_label284 RTLNAME clefia_clefia_Pipeline_ByteXor_label284}
  {SRCNAME clefia_Pipeline_ByteCpy_label185 MODELNAME clefia_Pipeline_ByteCpy_label185 RTLNAME clefia_clefia_Pipeline_ByteCpy_label185}
  {SRCNAME clefia_Pipeline_ByteXor_label286 MODELNAME clefia_Pipeline_ByteXor_label286 RTLNAME clefia_clefia_Pipeline_ByteXor_label286}
  {SRCNAME clefia_Pipeline_ByteCpy_label187 MODELNAME clefia_Pipeline_ByteCpy_label187 RTLNAME clefia_clefia_Pipeline_ByteCpy_label187}
  {SRCNAME clefia_Pipeline_ByteXor_label288 MODELNAME clefia_Pipeline_ByteXor_label288 RTLNAME clefia_clefia_Pipeline_ByteXor_label288}
  {SRCNAME clefia_Pipeline_ByteXor_label289 MODELNAME clefia_Pipeline_ByteXor_label289 RTLNAME clefia_clefia_Pipeline_ByteXor_label289}
  {SRCNAME clefia_Pipeline_ByteCpy_label190 MODELNAME clefia_Pipeline_ByteCpy_label190 RTLNAME clefia_clefia_Pipeline_ByteCpy_label190}
  {SRCNAME clefia_Pipeline_ByteXor_label291 MODELNAME clefia_Pipeline_ByteXor_label291 RTLNAME clefia_clefia_Pipeline_ByteXor_label291}
  {SRCNAME clefia_Pipeline_ByteCpy_label192 MODELNAME clefia_Pipeline_ByteCpy_label192 RTLNAME clefia_clefia_Pipeline_ByteCpy_label192}
  {SRCNAME clefia_Pipeline_ByteXor_label293 MODELNAME clefia_Pipeline_ByteXor_label293 RTLNAME clefia_clefia_Pipeline_ByteXor_label293}
  {SRCNAME clefia_Pipeline_ByteXor_label294 MODELNAME clefia_Pipeline_ByteXor_label294 RTLNAME clefia_clefia_Pipeline_ByteXor_label294}
  {SRCNAME clefia_Pipeline_ByteCpy_label195 MODELNAME clefia_Pipeline_ByteCpy_label195 RTLNAME clefia_clefia_Pipeline_ByteCpy_label195}
  {SRCNAME clefia_Pipeline_ByteXor_label296 MODELNAME clefia_Pipeline_ByteXor_label296 RTLNAME clefia_clefia_Pipeline_ByteXor_label296}
  {SRCNAME clefia_Pipeline_ByteCpy_label197 MODELNAME clefia_Pipeline_ByteCpy_label197 RTLNAME clefia_clefia_Pipeline_ByteCpy_label197}
  {SRCNAME clefia_Pipeline_ByteCpy_label198 MODELNAME clefia_Pipeline_ByteCpy_label198 RTLNAME clefia_clefia_Pipeline_ByteCpy_label198}
  {SRCNAME clefia_Pipeline_ByteCpy_label1113 MODELNAME clefia_Pipeline_ByteCpy_label1113 RTLNAME clefia_clefia_Pipeline_ByteCpy_label1113}
  {SRCNAME clefia_Pipeline_ByteXor_label2114 MODELNAME clefia_Pipeline_ByteXor_label2114 RTLNAME clefia_clefia_Pipeline_ByteXor_label2114}
  {SRCNAME clefia_Pipeline_ByteXor_label2115 MODELNAME clefia_Pipeline_ByteXor_label2115 RTLNAME clefia_clefia_Pipeline_ByteXor_label2115}
  {SRCNAME clefia_Pipeline_ByteCpy_label1116 MODELNAME clefia_Pipeline_ByteCpy_label1116 RTLNAME clefia_clefia_Pipeline_ByteCpy_label1116}
  {SRCNAME clefia_Pipeline_ClefiaGfn4Inv_label5 MODELNAME clefia_Pipeline_ClefiaGfn4Inv_label5 RTLNAME clefia_clefia_Pipeline_ClefiaGfn4Inv_label5}
  {SRCNAME clefia_Pipeline_ByteCpy_label1117 MODELNAME clefia_Pipeline_ByteCpy_label1117 RTLNAME clefia_clefia_Pipeline_ByteCpy_label1117}
  {SRCNAME clefia_Pipeline_ByteCpy_label1118 MODELNAME clefia_Pipeline_ByteCpy_label1118 RTLNAME clefia_clefia_Pipeline_ByteCpy_label1118}
  {SRCNAME clefia_Pipeline_ByteXor_label2119 MODELNAME clefia_Pipeline_ByteXor_label2119 RTLNAME clefia_clefia_Pipeline_ByteXor_label2119}
  {SRCNAME clefia_Pipeline_ByteXor_label2120 MODELNAME clefia_Pipeline_ByteXor_label2120 RTLNAME clefia_clefia_Pipeline_ByteXor_label2120}
  {SRCNAME clefia MODELNAME clefia RTLNAME clefia IS_TOP 1
    SUBMODULES {
      {MODELNAME clefia_con128_ROM_AUTO_1R RTLNAME clefia_con128_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME clefia_clefia_s0_ROM_AUTO_1R RTLNAME clefia_clefia_s0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME clefia_clefia_s1_ROM_AUTO_1R RTLNAME clefia_clefia_s1_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME clefia_con192_ROM_AUTO_1R RTLNAME clefia_con192_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME clefia_con256_ROM_AUTO_1R RTLNAME clefia_con256_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME clefia_t_17_RAM_AUTO_1R1W RTLNAME clefia_t_17_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME clefia_fin_7_RAM_AUTO_1R1W RTLNAME clefia_fin_7_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME clefia_rin_1_RAM_AUTO_1R1W RTLNAME clefia_rin_1_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME clefia_rout_1_RAM_AUTO_1R1W RTLNAME clefia_rout_1_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME clefia_fin_6_RAM_AUTO_1R1W RTLNAME clefia_fin_6_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME clefia_fout_6_RAM_AUTO_1R1W RTLNAME clefia_fout_6_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME clefia_skey256_1_RAM_AUTO_1R1W RTLNAME clefia_skey256_1_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME clefia_rk_RAM_AUTO_1R1W RTLNAME clefia_rk_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME clefia_control_s_axi RTLNAME clefia_control_s_axi BINDTYPE interface TYPE interface_s_axilite}
    }
  }
}
