# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_dec/design_dec.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dec || ORIG_REF_NAME==design_dec} -quiet] -quiet

# IP: bd/design_dec/ip/design_dec_processing_system7_0_0/design_dec_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dec_processing_system7_0_0 || ORIG_REF_NAME==design_dec_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_dec/ip/design_dec_ps7_0_axi_periph_0/design_dec_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dec_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_dec_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_dec/ip/design_dec_rst_ps7_0_100M_0/design_dec_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dec_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_dec_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_dec/ip/design_dec_clefia_dec_0_0/design_dec_clefia_dec_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dec_clefia_dec_0_0 || ORIG_REF_NAME==design_dec_clefia_dec_0_0} -quiet] -quiet

# IP: bd/design_dec/ip/design_dec_auto_pc_0/design_dec_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dec_auto_pc_0 || ORIG_REF_NAME==design_dec_auto_pc_0} -quiet] -quiet

# XDC: d:/tmp/CLEFIA/CLEFIA_256/dec/dec.gen/sources_1/bd/design_dec/design_dec_ooc.xdc
