// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module clefia_ClefiaKeySet256 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        rk_address0,
        rk_ce0,
        rk_we0,
        rk_d0,
        rk_address1,
        rk_ce1,
        rk_q1
);

parameter    ap_ST_fsm_state1 = 15'd1;
parameter    ap_ST_fsm_state2 = 15'd2;
parameter    ap_ST_fsm_state3 = 15'd4;
parameter    ap_ST_fsm_state4 = 15'd8;
parameter    ap_ST_fsm_state5 = 15'd16;
parameter    ap_ST_fsm_state6 = 15'd32;
parameter    ap_ST_fsm_state7 = 15'd64;
parameter    ap_ST_fsm_state8 = 15'd128;
parameter    ap_ST_fsm_state9 = 15'd256;
parameter    ap_ST_fsm_state10 = 15'd512;
parameter    ap_ST_fsm_state11 = 15'd1024;
parameter    ap_ST_fsm_state12 = 15'd2048;
parameter    ap_ST_fsm_state13 = 15'd4096;
parameter    ap_ST_fsm_state14 = 15'd8192;
parameter    ap_ST_fsm_state15 = 15'd16384;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] rk_address0;
output   rk_ce0;
output   rk_we0;
output  [7:0] rk_d0;
output  [7:0] rk_address1;
output   rk_ce1;
input  [7:0] rk_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[7:0] rk_address0;
reg rk_ce0;
reg rk_we0;
reg[7:0] rk_d0;
reg[7:0] rk_address1;
reg rk_ce1;

(* fsm_encoding = "none" *) reg   [14:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] add_ln373_fu_196_p2;
reg   [3:0] add_ln373_reg_274;
wire    ap_CS_fsm_state7;
wire   [7:0] or_ln364_fu_202_p2;
reg   [7:0] or_ln364_reg_279;
wire   [0:0] icmp_ln373_fu_190_p2;
wire   [0:0] trunc_ln374_fu_210_p1;
reg   [0:0] trunc_ln374_reg_287;
wire   [0:0] tmp_fu_214_p3;
reg   [0:0] tmp_reg_291;
wire   [8:0] add_ln381_fu_234_p2;
reg   [8:0] add_ln381_reg_295;
reg   [4:0] fin_address0;
reg    fin_ce0;
reg    fin_we0;
reg   [7:0] fin_d0;
wire   [7:0] fin_q0;
reg    fin_ce1;
reg    fin_we1;
wire   [7:0] fin_q1;
reg   [4:0] fout_address0;
reg    fout_ce0;
reg    fout_we0;
wire   [7:0] fout_q0;
reg    fout_ce1;
reg    fout_we1;
wire   [7:0] fout_q1;
reg   [4:0] lk_address0;
reg    lk_ce0;
reg    lk_we0;
reg   [7:0] lk_d0;
wire   [7:0] lk_q0;
reg    lk_ce1;
wire   [7:0] lk_q1;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1_fu_84_ap_start;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1_fu_84_ap_done;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1_fu_84_ap_idle;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1_fu_84_ap_ready;
wire   [4:0] grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1_fu_84_fin_address0;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1_fu_84_fin_ce0;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1_fu_84_fin_we0;
wire   [7:0] grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1_fu_84_fin_d0;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_ap_start;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_ap_done;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_ap_idle;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_ap_ready;
wire   [4:0] grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fin_address0;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fin_ce0;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fin_we0;
wire   [7:0] grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fin_d0;
wire   [4:0] grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fin_address1;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fin_ce1;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fin_we1;
wire   [7:0] grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fin_d1;
wire   [4:0] grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fout_address0;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fout_ce0;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fout_we0;
wire   [7:0] grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fout_d0;
wire   [4:0] grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fout_address1;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fout_ce1;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fout_we1;
wire   [7:0] grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fout_d1;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_1_fu_104_ap_start;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_1_fu_104_ap_done;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_1_fu_104_ap_idle;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_1_fu_104_ap_ready;
wire   [7:0] grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_1_fu_104_rk_address0;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_1_fu_104_rk_ce0;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_1_fu_104_rk_we0;
wire   [7:0] grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_1_fu_104_rk_d0;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_ap_start;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_ap_done;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_ap_idle;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_ap_ready;
wire   [4:0] grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_fout_address0;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_fout_ce0;
wire   [4:0] grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_lk_address0;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_lk_ce0;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_lk_we0;
wire   [7:0] grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_lk_d0;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_ap_start;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_ap_done;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_ap_idle;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_ap_ready;
wire   [4:0] grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_lk_address0;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_lk_ce0;
wire   [7:0] grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_rk_address0;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_rk_ce0;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_rk_we0;
wire   [7:0] grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_rk_d0;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_ap_start;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_ap_done;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_ap_idle;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_ap_ready;
wire   [4:0] grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_lk_address0;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_lk_ce0;
wire   [7:0] grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_rk_address0;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_rk_ce0;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_rk_we0;
wire   [7:0] grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_rk_d0;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_ap_start;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_ap_done;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_ap_idle;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_ap_ready;
wire   [7:0] grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_rk_address0;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_rk_ce0;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_rk_we0;
wire   [7:0] grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_rk_d0;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_ap_start;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_ap_done;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_ap_idle;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_ap_ready;
wire   [7:0] grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_rk_address0;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_rk_ce0;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_rk_we0;
wire   [7:0] grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_rk_d0;
wire   [7:0] grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_rk_address1;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_rk_ce1;
wire    grp_ClefiaDoubleSwap_1_fu_157_ap_start;
wire    grp_ClefiaDoubleSwap_1_fu_157_ap_done;
wire    grp_ClefiaDoubleSwap_1_fu_157_ap_idle;
wire    grp_ClefiaDoubleSwap_1_fu_157_ap_ready;
wire   [4:0] grp_ClefiaDoubleSwap_1_fu_157_lk_address0;
wire    grp_ClefiaDoubleSwap_1_fu_157_lk_ce0;
wire    grp_ClefiaDoubleSwap_1_fu_157_lk_we0;
wire   [7:0] grp_ClefiaDoubleSwap_1_fu_157_lk_d0;
wire   [4:0] grp_ClefiaDoubleSwap_1_fu_157_lk_address1;
wire    grp_ClefiaDoubleSwap_1_fu_157_lk_ce1;
reg   [4:0] grp_ClefiaDoubleSwap_1_fu_157_lk_offset;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_ap_start;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_ap_done;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_ap_idle;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_ap_ready;
wire   [7:0] grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_rk_address0;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_rk_ce0;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_rk_we0;
wire   [7:0] grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_rk_d0;
wire   [7:0] grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_rk_address1;
wire    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_rk_ce1;
reg    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1_fu_84_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_1_fu_104_ap_start_reg;
reg    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_ap_start_reg;
wire    ap_CS_fsm_state8;
reg    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_ap_start_reg;
wire    ap_CS_fsm_state12;
reg    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_ap_start_reg;
wire    ap_CS_fsm_state15;
reg    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg    grp_ClefiaDoubleSwap_1_fu_157_ap_start_reg;
reg    ap_block_state10_on_subcall_done;
wire    ap_CS_fsm_state14;
reg    ap_block_state14_on_subcall_done;
wire    ap_CS_fsm_state11;
reg    grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_ap_start_reg;
wire    ap_CS_fsm_state13;
reg   [7:0] idx35_fu_64;
wire   [7:0] add_ln387_fu_242_p2;
reg    ap_block_state11_on_subcall_done;
reg   [3:0] i_fu_68;
wire   [7:0] shl_ln_fu_222_p3;
wire   [8:0] zext_ln381_fu_230_p1;
reg   [14:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_block_state4_on_subcall_done;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 15'd1;
#0 grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1_fu_84_ap_start_reg = 1'b0;
#0 grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_ap_start_reg = 1'b0;
#0 grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_1_fu_104_ap_start_reg = 1'b0;
#0 grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_ap_start_reg = 1'b0;
#0 grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_ap_start_reg = 1'b0;
#0 grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_ap_start_reg = 1'b0;
#0 grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_ap_start_reg = 1'b0;
#0 grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_ap_start_reg = 1'b0;
#0 grp_ClefiaDoubleSwap_1_fu_157_ap_start_reg = 1'b0;
#0 grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_ap_start_reg = 1'b0;
end

clefia_ClefiaKeySet256_fin_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
fin_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fin_address0),
    .ce0(fin_ce0),
    .we0(fin_we0),
    .d0(fin_d0),
    .q0(fin_q0),
    .address1(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fin_address1),
    .ce1(fin_ce1),
    .we1(fin_we1),
    .d1(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fin_d1),
    .q1(fin_q1)
);

clefia_ClefiaKeySet256_fin_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
fout_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fout_address0),
    .ce0(fout_ce0),
    .we0(fout_we0),
    .d0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fout_d0),
    .q0(fout_q0),
    .address1(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fout_address1),
    .ce1(fout_ce1),
    .we1(fout_we1),
    .d1(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fout_d1),
    .q1(fout_q1)
);

clefia_ClefiaKeySet256_lk_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
lk_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lk_address0),
    .ce0(lk_ce0),
    .we0(lk_we0),
    .d0(lk_d0),
    .q0(lk_q0),
    .address1(grp_ClefiaDoubleSwap_1_fu_157_lk_address1),
    .ce1(lk_ce1),
    .q1(lk_q1)
);

clefia_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1 grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1_fu_84(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1_fu_84_ap_start),
    .ap_done(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1_fu_84_ap_done),
    .ap_idle(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1_fu_84_ap_idle),
    .ap_ready(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1_fu_84_ap_ready),
    .fin_address0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1_fu_84_fin_address0),
    .fin_ce0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1_fu_84_fin_ce0),
    .fin_we0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1_fu_84_fin_we0),
    .fin_d0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1_fu_84_fin_d0)
);

clefia_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1 grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_ap_start),
    .ap_done(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_ap_done),
    .ap_idle(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_ap_idle),
    .ap_ready(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_ap_ready),
    .fin_address0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fin_address0),
    .fin_ce0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fin_ce0),
    .fin_we0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fin_we0),
    .fin_d0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fin_d0),
    .fin_q0(fin_q0),
    .fin_address1(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fin_address1),
    .fin_ce1(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fin_ce1),
    .fin_we1(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fin_we1),
    .fin_d1(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fin_d1),
    .fin_q1(fin_q1),
    .fout_address0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fout_address0),
    .fout_ce0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fout_ce0),
    .fout_we0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fout_we0),
    .fout_d0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fout_d0),
    .fout_q0(fout_q0),
    .fout_address1(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fout_address1),
    .fout_ce1(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fout_ce1),
    .fout_we1(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fout_we1),
    .fout_d1(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fout_d1),
    .fout_q1(fout_q1)
);

clefia_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_1 grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_1_fu_104(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_1_fu_104_ap_start),
    .ap_done(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_1_fu_104_ap_done),
    .ap_idle(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_1_fu_104_ap_idle),
    .ap_ready(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_1_fu_104_ap_ready),
    .rk_address0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_1_fu_104_rk_address0),
    .rk_ce0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_1_fu_104_rk_ce0),
    .rk_we0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_1_fu_104_rk_we0),
    .rk_d0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_1_fu_104_rk_d0)
);

clefia_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13 grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_ap_start),
    .ap_done(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_ap_done),
    .ap_idle(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_ap_idle),
    .ap_ready(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_ap_ready),
    .fout_address0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_fout_address0),
    .fout_ce0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_fout_ce0),
    .fout_q0(fout_q0),
    .lk_address0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_lk_address0),
    .lk_ce0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_lk_ce0),
    .lk_we0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_lk_we0),
    .lk_d0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_lk_d0)
);

clefia_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16 grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_ap_start),
    .ap_done(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_ap_done),
    .ap_idle(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_ap_idle),
    .ap_ready(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_ap_ready),
    .add_ln381(add_ln381_reg_295),
    .lk_address0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_lk_address0),
    .lk_ce0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_lk_ce0),
    .lk_q0(lk_q0),
    .or_ln364(or_ln364_reg_279),
    .rk_address0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_rk_address0),
    .rk_ce0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_rk_ce0),
    .rk_we0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_rk_we0),
    .rk_d0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_rk_d0)
);

clefia_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14 grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_ap_start),
    .ap_done(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_ap_done),
    .ap_idle(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_ap_idle),
    .ap_ready(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_ap_ready),
    .add_ln381(add_ln381_reg_295),
    .lk_address0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_lk_address0),
    .lk_ce0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_lk_ce0),
    .lk_q0(lk_q0),
    .or_ln364(or_ln364_reg_279),
    .rk_address0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_rk_address0),
    .rk_ce0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_rk_ce0),
    .rk_we0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_rk_we0),
    .rk_d0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_rk_d0)
);

clefia_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18 grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_ap_start),
    .ap_done(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_ap_done),
    .ap_idle(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_ap_idle),
    .ap_ready(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_ap_ready),
    .rk_address0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_rk_address0),
    .rk_ce0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_rk_ce0),
    .rk_we0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_rk_we0),
    .rk_d0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_rk_d0)
);

clefia_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17 grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_ap_start),
    .ap_done(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_ap_done),
    .ap_idle(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_ap_idle),
    .ap_ready(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_ap_ready),
    .or_ln364(or_ln364_reg_279),
    .rk_address0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_rk_address0),
    .rk_ce0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_rk_ce0),
    .rk_we0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_rk_we0),
    .rk_d0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_rk_d0),
    .rk_address1(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_rk_address1),
    .rk_ce1(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_rk_ce1),
    .rk_q1(rk_q1)
);

clefia_ClefiaDoubleSwap_1 grp_ClefiaDoubleSwap_1_fu_157(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ClefiaDoubleSwap_1_fu_157_ap_start),
    .ap_done(grp_ClefiaDoubleSwap_1_fu_157_ap_done),
    .ap_idle(grp_ClefiaDoubleSwap_1_fu_157_ap_idle),
    .ap_ready(grp_ClefiaDoubleSwap_1_fu_157_ap_ready),
    .lk_address0(grp_ClefiaDoubleSwap_1_fu_157_lk_address0),
    .lk_ce0(grp_ClefiaDoubleSwap_1_fu_157_lk_ce0),
    .lk_we0(grp_ClefiaDoubleSwap_1_fu_157_lk_we0),
    .lk_d0(grp_ClefiaDoubleSwap_1_fu_157_lk_d0),
    .lk_q0(lk_q0),
    .lk_address1(grp_ClefiaDoubleSwap_1_fu_157_lk_address1),
    .lk_ce1(grp_ClefiaDoubleSwap_1_fu_157_lk_ce1),
    .lk_q1(lk_q1),
    .lk_offset(grp_ClefiaDoubleSwap_1_fu_157_lk_offset)
);

clefia_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15 grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_ap_start),
    .ap_done(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_ap_done),
    .ap_idle(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_ap_idle),
    .ap_ready(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_ap_ready),
    .or_ln364(or_ln364_reg_279),
    .rk_address0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_rk_address0),
    .rk_ce0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_rk_ce0),
    .rk_we0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_rk_we0),
    .rk_d0(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_rk_d0),
    .rk_address1(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_rk_address1),
    .rk_ce1(grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_rk_ce1),
    .rk_q1(rk_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ClefiaDoubleSwap_1_fu_157_ap_start_reg <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_state14_on_subcall_done) & (1'b1 == ap_CS_fsm_state14)) | ((1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10)))) begin
            grp_ClefiaDoubleSwap_1_fu_157_ap_start_reg <= 1'b1;
        end else if ((grp_ClefiaDoubleSwap_1_fu_157_ap_ready == 1'b1)) begin
            grp_ClefiaDoubleSwap_1_fu_157_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_ap_start_reg <= 1'b1;
        end else if ((grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_ap_ready == 1'b1)) begin
            grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1_fu_84_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1_fu_84_ap_start_reg <= 1'b1;
        end else if ((grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1_fu_84_ap_ready == 1'b1)) begin
            grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1_fu_84_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_ap_start_reg <= 1'b0;
    end else begin
        if (((tmp_fu_214_p3 == 1'd1) & (icmp_ln373_fu_190_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
            grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_ap_start_reg <= 1'b1;
        end else if ((grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_ap_ready == 1'b1)) begin
            grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_ap_start_reg <= 1'b1;
        end else if ((grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_ap_ready == 1'b1)) begin
            grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_ap_start_reg <= 1'b0;
    end else begin
        if (((tmp_fu_214_p3 == 1'd0) & (icmp_ln373_fu_190_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
            grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_ap_start_reg <= 1'b1;
        end else if ((grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_ap_ready == 1'b1)) begin
            grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_ap_start_reg <= 1'b1;
        end else if ((grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_ap_ready == 1'b1)) begin
            grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln373_fu_190_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
            grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_ap_start_reg <= 1'b1;
        end else if ((grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_ap_ready == 1'b1)) begin
            grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_1_fu_104_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_1_fu_104_ap_start_reg <= 1'b1;
        end else if ((grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_1_fu_104_ap_ready == 1'b1)) begin
            grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_1_fu_104_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_ap_start_reg <= 1'b1;
        end else if ((grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_ap_ready == 1'b1)) begin
            grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_68 <= 4'd0;
    end else if (((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11))) begin
        i_fu_68 <= add_ln373_reg_274;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        idx35_fu_64 <= 8'd0;
    end else if (((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11))) begin
        idx35_fu_64 <= add_ln387_fu_242_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        add_ln373_reg_274 <= add_ln373_fu_196_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln373_fu_190_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        add_ln381_reg_295[8 : 4] <= add_ln381_fu_234_p2[8 : 4];
        or_ln364_reg_279[2 : 0] <= or_ln364_fu_202_p2[2 : 0];
or_ln364_reg_279[7 : 4] <= or_ln364_fu_202_p2[7 : 4];
        tmp_reg_291 <= i_fu_68[32'd1];
        trunc_ln374_reg_287 <= trunc_ln374_fu_210_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state10_on_subcall_done)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state11_on_subcall_done)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state14_on_subcall_done)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1_fu_84_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state4_on_subcall_done)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state15) & (grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_ap_done == 1'b1)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) & (grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fin_address0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fin_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        fin_address0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1_fu_84_fin_address0;
    end else begin
        fin_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fin_ce0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fin_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        fin_ce0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1_fu_84_fin_ce0;
    end else begin
        fin_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fin_ce1 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fin_ce1;
    end else begin
        fin_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fin_d0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fin_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        fin_d0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1_fu_84_fin_d0;
    end else begin
        fin_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fin_we0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fin_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        fin_we0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1_fu_84_fin_we0;
    end else begin
        fin_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fin_we1 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fin_we1;
    end else begin
        fin_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        fout_address0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_fout_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        fout_address0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fout_address0;
    end else begin
        fout_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        fout_ce0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_fout_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        fout_ce0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fout_ce0;
    end else begin
        fout_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fout_ce1 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fout_ce1;
    end else begin
        fout_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fout_we0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fout_we0;
    end else begin
        fout_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fout_we1 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_fout_we1;
    end else begin
        fout_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        if ((tmp_reg_291 == 1'd1)) begin
            grp_ClefiaDoubleSwap_1_fu_157_lk_offset = 5'd16;
        end else if ((tmp_reg_291 == 1'd0)) begin
            grp_ClefiaDoubleSwap_1_fu_157_lk_offset = 5'd0;
        end else begin
            grp_ClefiaDoubleSwap_1_fu_157_lk_offset = 'bx;
        end
    end else begin
        grp_ClefiaDoubleSwap_1_fu_157_lk_offset = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_reg_291 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((tmp_reg_291 == 1'd0) & (1'b1 == ap_CS_fsm_state11)))) begin
        lk_address0 = grp_ClefiaDoubleSwap_1_fu_157_lk_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        lk_address0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_lk_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        lk_address0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_lk_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        lk_address0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_lk_address0;
    end else begin
        lk_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_reg_291 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((tmp_reg_291 == 1'd0) & (1'b1 == ap_CS_fsm_state11)))) begin
        lk_ce0 = grp_ClefiaDoubleSwap_1_fu_157_lk_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        lk_ce0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_lk_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        lk_ce0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_lk_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        lk_ce0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_lk_ce0;
    end else begin
        lk_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_reg_291 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((tmp_reg_291 == 1'd0) & (1'b1 == ap_CS_fsm_state11)))) begin
        lk_ce1 = grp_ClefiaDoubleSwap_1_fu_157_lk_ce1;
    end else begin
        lk_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_reg_291 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((tmp_reg_291 == 1'd0) & (1'b1 == ap_CS_fsm_state11)))) begin
        lk_d0 = grp_ClefiaDoubleSwap_1_fu_157_lk_d0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        lk_d0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_lk_d0;
    end else begin
        lk_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_reg_291 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((tmp_reg_291 == 1'd0) & (1'b1 == ap_CS_fsm_state11)))) begin
        lk_we0 = grp_ClefiaDoubleSwap_1_fu_157_lk_we0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        lk_we0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_lk_we0;
    end else begin
        lk_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln374_reg_287 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        rk_address0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_rk_address0;
    end else if (((trunc_ln374_reg_287 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
        rk_address0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_rk_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        rk_address0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_rk_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        rk_address0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_rk_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        rk_address0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_rk_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        rk_address0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_1_fu_104_rk_address0;
    end else begin
        rk_address0 = 'bx;
    end
end

always @ (*) begin
    if ((trunc_ln374_reg_287 == 1'd1)) begin
        if ((1'b1 == ap_CS_fsm_state14)) begin
            rk_address1 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_rk_address1;
        end else if ((1'b1 == ap_CS_fsm_state10)) begin
            rk_address1 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_rk_address1;
        end else begin
            rk_address1 = 'bx;
        end
    end else begin
        rk_address1 = 'bx;
    end
end

always @ (*) begin
    if (((trunc_ln374_reg_287 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        rk_ce0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_rk_ce0;
    end else if (((trunc_ln374_reg_287 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
        rk_ce0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_rk_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        rk_ce0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_rk_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        rk_ce0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_rk_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        rk_ce0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_rk_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        rk_ce0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_1_fu_104_rk_ce0;
    end else begin
        rk_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((trunc_ln374_reg_287 == 1'd1)) begin
        if ((1'b1 == ap_CS_fsm_state14)) begin
            rk_ce1 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_rk_ce1;
        end else if ((1'b1 == ap_CS_fsm_state10)) begin
            rk_ce1 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_rk_ce1;
        end else begin
            rk_ce1 = 1'b0;
        end
    end else begin
        rk_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln374_reg_287 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        rk_d0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_rk_d0;
    end else if (((trunc_ln374_reg_287 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
        rk_d0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_rk_d0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        rk_d0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_rk_d0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        rk_d0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_rk_d0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        rk_d0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_rk_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        rk_d0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_1_fu_104_rk_d0;
    end else begin
        rk_d0 = 'bx;
    end
end

always @ (*) begin
    if (((trunc_ln374_reg_287 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        rk_we0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_rk_we0;
    end else if (((trunc_ln374_reg_287 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
        rk_we0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_rk_we0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        rk_we0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_rk_we0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        rk_we0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_rk_we0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        rk_we0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_rk_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        rk_we0 = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_1_fu_104_rk_we0;
    end else begin
        rk_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1_fu_84_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((tmp_fu_214_p3 == 1'd1) & (icmp_ln373_fu_190_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else if (((tmp_fu_214_p3 == 1'd0) & (icmp_ln373_fu_190_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((trunc_ln374_reg_287 == 1'd0) & (1'b1 == ap_CS_fsm_state8) & (grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else if (((trunc_ln374_reg_287 == 1'd1) & (1'b1 == ap_CS_fsm_state8) & (grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((trunc_ln374_reg_287 == 1'd0) & (1'b1 == ap_CS_fsm_state12) & (grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else if (((trunc_ln374_reg_287 == 1'd1) & (1'b1 == ap_CS_fsm_state12) & (grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((1'b0 == ap_block_state14_on_subcall_done) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((1'b1 == ap_CS_fsm_state15) & (grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln373_fu_196_p2 = (i_fu_68 + 4'd1);

assign add_ln381_fu_234_p2 = (zext_ln381_fu_230_p1 + 9'd160);

assign add_ln387_fu_242_p2 = (idx35_fu_64 + 8'd16);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state10_on_subcall_done = ((trunc_ln374_reg_287 == 1'd1) & (grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state11_on_subcall_done = (((tmp_reg_291 == 1'd1) & (grp_ClefiaDoubleSwap_1_fu_157_ap_done == 1'b0)) | ((tmp_reg_291 == 1'd0) & (grp_ClefiaDoubleSwap_1_fu_157_ap_done == 1'b0)));
end

always @ (*) begin
    ap_block_state14_on_subcall_done = ((trunc_ln374_reg_287 == 1'd1) & (grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state4_on_subcall_done = ((grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_1_fu_104_ap_done == 1'b0) | (grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_ap_done == 1'b0));
end

assign grp_ClefiaDoubleSwap_1_fu_157_ap_start = grp_ClefiaDoubleSwap_1_fu_157_ap_start_reg;

assign grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_ap_start = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_13_fu_112_ap_start_reg;

assign grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1_fu_84_ap_start = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_116_1_fu_84_ap_start_reg;

assign grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_ap_start = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_14_fu_129_ap_start_reg;

assign grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_ap_start = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_15_fu_165_ap_start_reg;

assign grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_ap_start = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_16_fu_118_ap_start_reg;

assign grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_ap_start = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_17_fu_148_ap_start_reg;

assign grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_ap_start = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_18_fu_140_ap_start_reg;

assign grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_1_fu_104_ap_start = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_123_1_fu_104_ap_start_reg;

assign grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_ap_start = grp_ClefiaKeySet256_Pipeline_VITIS_LOOP_210_1_fu_92_ap_start_reg;

assign icmp_ln373_fu_190_p2 = ((i_fu_68 == 4'd13) ? 1'b1 : 1'b0);

assign or_ln364_fu_202_p2 = (idx35_fu_64 | 8'd8);

assign shl_ln_fu_222_p3 = {{i_fu_68}, {4'd0}};

assign tmp_fu_214_p3 = i_fu_68[32'd1];

assign trunc_ln374_fu_210_p1 = i_fu_68[0:0];

assign zext_ln381_fu_230_p1 = shl_ln_fu_222_p3;

always @ (posedge ap_clk) begin
    or_ln364_reg_279[3] <= 1'b1;
    add_ln381_reg_295[3:0] <= 4'b0000;
end

endmodule //clefia_ClefiaKeySet256
